In [ ]:
library

In [1]:
import numpy as np
import tensorflow as tf

membuat tensor dengan shape[5,5] dengan nilai random simpan kedalam variabel random tensor

In [2]:
random_tensor = tf.random.normal([5,5], mean=0, stddev=1, seed=1)
random_tensor

<tf.Tensor: shape=(5, 5), dtype=float32, numpy=
array([[-0.8113182 ,  1.4845988 ,  0.06532937, -2.4427042 ,  0.0992484 ],
       [ 0.5912243 ,  0.59282297, -2.1229296 , -0.72289723, -0.05627038],
       [ 0.6435448 , -0.26432407,  1.8566332 ,  0.5678417 , -0.3828359 ],
       [-1.4853433 ,  1.2617711 , -0.02530608, -0.2646297 ,  1.5328138 ],
       [-1.7429771 , -0.43789294, -0.56601   ,  0.32066926,  1.132831  ]],
      dtype=float32)>

nilai prime tensor dalam variabel primer= tensor

In [30]:
p_tensor = tf.constant([ 11, 13, 17, 19, 23, 29, 31, 37, 41, 43, 47, 53, 59, 61, 71, 73, 79, 83, 89,97, 101,103,105,107,109], shape=[5, 5], dtype=tf.float32)
p_tensor

<tf.Tensor: shape=(5, 5), dtype=float32, numpy=
array([[ 11.,  13.,  17.,  19.,  23.],
       [ 29.,  31.,  37.,  41.,  43.],
       [ 47.,  53.,  59.,  61.,  71.],
       [ 73.,  79.,  83.,  89.,  97.],
       [101., 103., 105., 107., 109.]], dtype=float32)>

aritmatika 5 operator

In [31]:
#penjumlahan
print(tf.add(random_tensor, p_tensor))
#perkalian
print(tf.multiply(random_tensor, p_tensor))
#pangkat
print(tf.pow(random_tensor, p_tensor))
#pembagian
print(tf.divide(random_tensor, p_tensor))
#logaritma
print(tf.math.log(random_tensor, p_tensor))


tf.Tensor(
[[ 10.188682  14.484599  17.065329  16.557297  23.099249]
 [ 29.591225  31.592823  34.87707   40.277103  42.94373 ]
 [ 47.643543  52.735676  60.856632  61.56784   70.617165]
 [ 71.514656  80.26177   82.97469   88.73537   98.532814]
 [ 99.25702  102.5621   104.43399  107.32067  110.13283 ]], shape=(5, 5), dtype=float32)
tf.Tensor(
[[  -8.9245      19.299784     1.1105993  -46.41138      2.2827132]
 [  17.145506    18.377512   -78.54839    -29.638786    -2.4196262]
 [  30.246605   -14.009175   109.54136     34.638344   -27.181349 ]
 [-108.43006     99.67992     -2.1004045  -23.552042   148.68294  ]
 [-176.0407     -45.102974   -59.43105     34.31161    123.47858  ]], shape=(5, 5), dtype=float32)
tf.Tensor(
[[-1.0025442e-01  1.7018379e+02  7.1919113e-21 -2.3417834e+07
   8.4069995e-24]
 [ 2.4033457e-07  9.1343090e-08 -1.2491561e+12 -1.6677810e-06
   0.0000000e+00]
 [ 1.0074017e-09 -2.3618141e-31  7.1588032e+15  1.0182739e-15
  -2.4768415e-30]
 [-3.4943004e+12  9.4943456e+07  0.

minimal variabel random tensor

In [32]:
argmin_random = tf.random.normal([5,5])
print("input nilai random tensor:",argmin_random.numpy())
min_random_1 = tf.argmin(argmin_random, axis = 0)
min_random_2 = tf.argmin(argmin_random, axis = 1)
print("minimum  kolom:",min_random_1.numpy())
print("minimum baris:",min_random_2.numpy())

input nilai random tensor: [[-8.3187354e-01 -1.6663276e-01 -1.0227603e+00  1.1154273e+00
  -1.5401505e+00]
 [ 1.1667961e+00  1.1972224e+00 -6.0550570e-01  2.1365252e+00
   9.2129959e-03]
 [ 7.2915020e-04  7.2323895e-01  2.3559124e+00 -1.4757367e+00
  -7.6721042e-01]
 [ 1.4862822e+00  5.7590759e-01 -4.9723676e-01  1.0523846e+00
   1.5885700e-01]
 [-4.7553068e-01  1.9022655e-01 -5.3307408e-01 -1.7528910e-03
   4.4860047e-01]]
minimum  kolom: [0 0 0 2 0]
minimum baris: [4 2 3 2 2]


maksimal variabel random tensr

In [33]:
argmax_random = tf.random.normal([5,5])
print("input nilai random tensor:",argmax_random.numpy())
max_random_1 = tf.argmax(argmax_random, axis = 0)
max_random_2 = tf.argmax(argmax_random, axis = 1)
print("maximum  kolom:",max_random_1.numpy())
print("maximum  baris:",max_random_2.numpy())

input nilai random tensor: [[-0.94948053  1.4503782   0.15042911 -0.05650275  0.6821406 ]
 [-0.8233773   1.0154779   0.360747    1.2136923   0.15672112]
 [-0.9829058   0.09580301  0.5180905   0.5234288  -1.5193932 ]
 [-1.7666095  -2.3131227   0.30660167 -0.95632076  0.7514335 ]
 [ 1.0150648  -0.5964415  -1.1884435  -0.23886323  0.9556259 ]]
maximum  kolom: [4 0 2 1 4]
maximum  baris: [1 3 3 4 0]


sorting kedua variabel deskending

In [44]:
random_tensor = tf.random.normal([5,5], mean=0, stddev=1, seed=1)
print("input random tensor:",random_tensor.numpy())
p_tensor = tf.constant([ 11, 13, 17, 19, 23, 29, 31, 37, 41, 43, 47, 53, 59, 61, 71, 73, 79, 83, 89,97, 101,103,105,107,109], shape=[5, 5], dtype=tf.float32)
p_tensor
print("input prime tensor:",p_tensor.numpy())
sorted_random = tf.sort(random_tensor, direction = "DESCENDING")
print("sorting dengan descending (random):",sorted_random.numpy())
sorted_prime = tf.sort(p_tensor, direction = "DESCENDING")
print("sorting dengan descending(prime):",sorted_prime.numpy())

input random tensor: [[ 0.84333754 -1.7211728  -0.32960904  1.0788107  -1.6626061 ]
 [ 0.6971222   0.46777618 -1.2562007  -1.6510495  -0.18414494]
 [-1.2479274   1.5249633  -0.40648946  1.8363605   0.02757771]
 [-0.83237827  0.6233228  -0.02841046 -1.3248721   0.07207767]
 [-0.7539529  -0.9860456   0.9800038   0.57062733 -0.45596495]]
input prime tensor: [[ 11.  13.  17.  19.  23.]
 [ 29.  31.  37.  41.  43.]
 [ 47.  53.  59.  61.  71.]
 [ 73.  79.  83.  89.  97.]
 [101. 103. 105. 107. 109.]]
sorting dengan descending (random): [[ 1.0788107   0.84333754 -0.32960904 -1.6626061  -1.7211728 ]
 [ 0.6971222   0.46777618 -0.18414494 -1.2562007  -1.6510495 ]
 [ 1.8363605   1.5249633   0.02757771 -0.40648946 -1.2479274 ]
 [ 0.6233228   0.07207767 -0.02841046 -0.83237827 -1.3248721 ]
 [ 0.9800038   0.57062733 -0.45596495 -0.7539529  -0.9860456 ]]
sorting dengan descending(prime): [[ 23.  19.  17.  13.  11.]
 [ 43.  41.  37.  31.  29.]
 [ 71.  61.  59.  53.  47.]
 [ 97.  89.  83.  79.  73.]
 [10